version: '3'

services:
  well-level:
    build: .
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
